apiVersion: apps/v1
kind: Deployment
metadata:
  name: bps-auth
  namespace: ocpsuperapp-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: bps-auth
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/bps-auth-dev:latest
        imagePullPolicy: Always