apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-erp
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ecommerce-erp
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/ecommerce-erp-dev
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /var/lib/odoo
            name: cbe-odoo-volume
          - name: odoo-config-volume
            mountPath: /etc/odoo/odoo.conf
            subPath: odoo.conf
      volumes:
        - name: cbe-odoo-volume
          persistentVolumeClaim:
            claimName: cbe-odoo-pvc-dev
        - name: odoo-config-volume
          configMap:
            name: odoo-config
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ecommerce
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/ecommerce-dev
        imagePullPolicy: Always

