apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-server
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: pdf-server
        image: harbor.cbe.com.et/cbe-superapp/pdf-server-uat:latest
        imagePullPolicy: Always