apiVersion: apps/v1
kind: Deployment
metadata:
  name: split-payment
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: split-payment
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/split-payment-dev
        imagePullPolicy: Always

