apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-rate
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: exchange-rate
        image: harbor.cbe.com.et/cbe-superapp/exchange-rate-uat:latest
        imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: news
        image: harbor.cbe.com.et/cbe-superapp/news-uat:latest
        imagePullPolicy: Always