apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: redis
        volumeMounts:
          - mountPath: /data
            name: redis-pvc-qa
      volumes:
        - name: redis-pvc-qa
          persistentVolumeClaim:
            claimName: redis-pvc-qa