apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-utility
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: qa-utility
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/qa-utility-dev:latest
        imagePullPolicy: Always
